[custom.all.http-types]
type   = "local"
path   = "."
ipkg   = "http-types.ipkg"

[custom.all.http-server-api]
type   = "local"
path   = "http-server-api"
ipkg   = "http-server-api.ipkg"

[custom.all.async]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async.git"
commit = "latest:main"
ipkg   = "async.ipkg"

[custom.all.ilex]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ilex.git"
commit = "latest:main"
ipkg   = "ilex.ipkg"

[custom.all.async-posix]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-async.git"
commit = "latest:main"
ipkg   = "async-posix/async-posix.ipkg"
